### ISSUE TITLE
Question About 802.11mc

### ISSUE THREAD

**Issue by jameswolfeoliver** [Plinzen/android-rttmanager-sample#1]
Hey, cool sample project! 
I'm currently experimenting with Wi-Fi positioning and Wi-Fi RTT but I'm unable find a router that supports the 802.11mc standard. I'm wondering if you could help me find one?

Your help is greatly appreciated!

**Comment by Plinzen** [comment]
We have a custom board from Intel here for testing. But it's not public available. Sorry!

**Comment by jameswolfeoliver** [comment]
Okay, thanks anyways!
