### ISSUE TITLE
Devices used for the  Wi-Fi RTT app

### ISSUE THREAD

**Issue by filartrix** [Plinzen/android-rttmanager-sample#2]
Hi, 
could you please list in the readme the devices used?
For the smartphone there is an info (it uses Snapdragon 820), but for the Wi-Fi router used, there is no info.
Thank you

**Comment by ManuGira** [comment]
I was about the ask the same question. But we can find in closed issues https://github.com/Plinzen/android-rttmanager-sample/issues/1 that someone asked the same question a couple of weeks ago.

Unfortunatly Plinzen answerd that they are using a custom board from Intel for testing. But it's not public available.

Also, there is this demo video from intel, but it seems they are only speaking abount the network card and not the access point.
https://www.intel.com/content/www/us/en/wireless-network/indoor-wifi-location-tracking.html

I spent the afternoon searching for access point supporting 802.11mc. If you find some please let me know.

**Comment by Plinzen** [comment]
Yes, you're right. We've a custom Intel Board here for testing purposes. 
If you have information about some routers which public available, I would be happy if you can share them. 
Nevertheless, I'll update the documentation.
