### ISSUE TITLE
Devices that support 802.11mc for RTT

### ISSUE THREAD

**Issue by MGasztold** [Plinzen/android-rttmanager-sample#3]
Hello,

Is there any list of devices of known devices on which you tested your sample?

I am preparing to buy a device for installing Android P DP2 so I can start experimenting with RTT. I have read that Google Pixel 2 works with this API but this device is pretty expensive for me. 

Has anybody been successful on other devices, e.g. Nokia 6.1 (2018) that has Qualcomm Snapdragon 630 ?

I would be grateful for any answers. Thank you in advance.

**Comment by Plinzen** [comment]
Hmm, I don't think that the Nokia 6.1 will work. I have a 6.1 as well, but I am not able to install Android P on it (it's not in the supported list of beta devices: https://developer.android.com/preview/devices/), so I can't check. 

Nevertheless, I tried to install my old project (https://github.com/Plinzen/android-rttmanager-compat) on that phone and the result does not look promising. 

So, I think you're stick to Google Phones up to now.
